name: simpletpbmirror
version: 1
handle:
- compress:  if ( out_header["Content-type"]=="text/css" ) compress
- compress:  if ( out_header["Content-type"]=="text/javascript" ) compress
- compress:  if ( out_header["Content-type"]=="text/html" ) compress
cron:
        - description:  fetchrecenttpb
          url:  cron/fetchrecenttpb
          schedule: "0 22 * * 1-5"
        - description:  fetchtoptpb
          url:  cron/fetchtoptpb
          schedule: "0 21 * * 1-5"
        - description:  fetchoabt
          url:  cron/fetchoabt
          schedule: "0 23 * * 1-5" 
          

